language: php

php:
    - 5.6
	- 7.2
	- 7.3

env:
    - WP_VERSION=5.0.3 WP_MULTISITE=0

before_install:
    - git submodule update --init --recursive
    - sleep 5

before_script:
    - bash tests/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
    - if [[ ${TRAVIS_PHP_VERSION:0:3} == "5.3" ]]; then composer global require --dev phpunit/phpunit ^4; fi
    - if [[ ${TRAVIS_PHP_VERSION:0:3} == "5.6" ]]; then composer global require --dev phpunit/phpunit ^5; composer install; fi
    - if [ "${TRAVIS_PHP_VERSION:0:3}" -ge "7.2" ]; then composer global require --dev phpunit/phpunit ^6; composer install; fi

script: phpunit

notifications:
    email:
        recipients:
          - aramzs@hacktext.com
        on_success: change
        on_failure: always
