language: php

php:
  - 5.6
  - 7.2
  - 7.3

env:
    - WP_VERSION=5.0.3 WP_MULTISITE=0

before_install:
    - git submodule update --init --recursive
    - sleep 5

before_script:
    - bash tests/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION

script: phpunit

notifications:
    email:
        recipients:
          - aramzs@hacktext.com
        on_success: change
        on_failure: always
